config/routes.rb
Rails.application.routes.draw do
  resources :toreads

end

app/models/toread.rb
class Toread < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/toreads_controller.rb
class ToreadsController < ApplicationController
  before_action :set_toread, only: [:show, :edit, :update, :destroy]

  # GET /toreads
  # GET /toreads.json
  def index
    @toreads = Toread.all
  end

  # GET /toreads/1
  # GET /toreads/1.json
  def show
  end

  # GET /toreads/new
  def new
    @toread = Toread.new
  end

  # GET /toreads/1/edit
  def edit
  end

  # POST /toreads
  # POST /toreads.json
  def create
    @toread = Toread.new(toread_params)

    respond_to do |format|
      if @toread.save
        format.html { redirect_to @toread, notice: 'Toread was successfully created.' }
        format.json { render :show, status: :created, location: @toread }
      else
        format.html { render :new }
        format.json { render json: @toread.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /toreads/1
  # PATCH/PUT /toreads/1.json
  def update
    respond_to do |format|
      if @toread.update(toread_params)
        format.html { redirect_to @toread, notice: 'Toread was successfully updated.' }
        format.json { render :show, status: :ok, location: @toread }
      else
        format.html { render :edit }
        format.json { render json: @toread.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /toreads/1
  # DELETE /toreads/1.json
  def destroy
    @toread.destroy
    respond_to do |format|
      format.html { redirect_to toreads_url, notice: 'Toread was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_toread
      @toread = Toread.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def toread_params
      params.require(:toread).permit(:title, :description, :read)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/toreads_helper.rb
module ToreadsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>ToReadApp</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/toreads/_form.html.erb
<%= form_for(@toread) do |f| %>
  <% if @toread.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@toread.errors.count, "error") %> prohibited this toread from being saved:</h2>

      <ul>
      <% @toread.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>
  <div class="field">
    <%= f.label :read %><br>
    <%= f.check_box :read %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/toreads/edit.html.erb
<h1>Editing Toread</h1>

<%= render 'form' %>

<%= link_to 'Show', @toread %> |
<%= link_to 'Back', toreads_path %>

app/views/toreads/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Toreads</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Description</th>
      <th>Read</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @toreads.each do |toread| %>
      <tr>
        <td><%= toread.title %></td>
        <td><%= toread.description %></td>
        <td><%= toread.read %></td>
        <td><%= link_to 'Show', toread %></td>
        <td><%= link_to 'Edit', edit_toread_path(toread) %></td>
        <td><%= link_to 'Destroy', toread, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Toread', new_toread_path %>

app/views/toreads/new.html.erb
<h1>New Toread</h1>

<%= render 'form' %>

<%= link_to 'Back', toreads_path %>

app/views/toreads/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @toread.title %>
</p>

<p>
  <strong>Description:</strong>
  <%= @toread.description %>
</p>

<p>
  <strong>Read:</strong>
  <%= @toread.read %>
</p>

<%= link_to 'Edit', edit_toread_path(@toread) %> |
<%= link_to 'Back', toreads_path %>